[project]
name = "simba"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cloudscraper>=1.2.71",
    "discord>=2.3.2",
    "dotenv>=0.9.9",
    "langchain>=1.4.2",
    "langchain-aws>=1.7.8",
    "langchain-openai>=1.6.2",
    "langchain-tavily>=0.2.18",
    "openai>=2.14.0",
]
